language: c

os:
  - linux

before_install:
  - wget https://cmocka.org/files/1.0/cmocka-1.0.1.tar.xz
  - tar -xJvf cmocka-1.0.1.tar.xz
  - cd cmocka-1.0.1 && mkdir build && cd build
  - cmake -DCMAKE_INSTALL_PREFIX:PATH=/usr ..
  - sudo make install
  - cd ../..
  - autoreconf -i

script: ./configure && make && make check
